task: gpqa_astro
tag:
  - astrobench
dataset_path: Maxwell-Jia/gpqa-astro
test_split: train
process_docs: !function utils.process_docs

output_type: generate_until
doc_to_text: "{{query}}"
doc_to_target: "{{answer}}"

filter_list:
  - name: "extract-answer"
    filter:
      - function: "regex"
        regex_pattern: "Answer:\\s*([A-D])|(?:^|[^A-Za-z])([A-D])(?:[^A-Za-z]|$)"
        fallback: "[invalid]"
      - function: "take_first"

metric_list:
  - metric: "exact_match"
    aggregation: "mean"
    higher_is_better: true

generation_kwargs:
  until:
    - "<|end_of_text|>"