task: super_gpqa_astro
tag:
  - astrobench
dataset_path: Maxwell-Jia/SuperGPQA-Astro
test_split: train
process_docs: !function utils.process_docs

output_type: generate_until
doc_to_text: "{{query}}"
doc_to_target: "{{answer}}"

filter_list:
  - name: "extract-answer"
    filter:
      - function: "regex"
        regex_pattern: "(?i)Answer:\\s*([A-J])"
        fallback: "[invalid]"
      - function: "take_last"

metric_list:
  - metric: "exact_match"
    aggregation: "mean"
    higher_is_better: true

generation_kwargs:
  until:
    - "<|end_of_text|>"